# Generated by Django 3.1 on 2020-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('checckin', models.CharField(max_length=200, null=True)),
                ('checkout', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
