# Generated by Django 3.1 on 2020-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='numberofpeople',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
