# Generated by Django 3.1 on 2020-09-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200830_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='Id',
        ),
    ]
